### ISSUE TITLE
LibISDBVersionHash.hppの無視設定

### ISSUE THREAD

**Issue by timarupopoka** [DBCTRADO/LibISDB#12]
更新お疲れさまです。
些細なことですが、LibISDBVersionHash.hppがgit管理下に入ってしまっています。
.gitignoreに拡張子.hppではなく.hで登録されているようです。

**Comment by DBCTRADO** [comment]
ありがとうございます。修正しました。

**Comment by timarupopoka** [comment]
対応ありがとうございます。
