### ISSUE TITLE
Windows上でのビルドエラー

### ISSUE THREAD

**Issue by estshorter** [DBCTRADO/LibISDB#7]
## 問題
最新版(8b98101fbfb036e137b4af0637d5c82bd7af5498) のビルドに失敗し、下記のエラーがでます。

```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	C2665	'std::make_error_code': 2 オーバーロードのどれも、すべての引数の型を変換できませんでした (ソース ファイルをコンパイルしています ..\LibISDB\Windows\Base\EDCBPluginWriter.cpp)	LibISDBWindows	C:\Users\thund\Documents\TV\TVTest2\src\LibISDB\LibISDB\Base\ErrorHandler.hpp	148	
エラー	C2665	'std::make_error_code': 2 オーバーロードのどれも、すべての引数の型を変換できませんでした (ソース ファイルをコンパイルしています ..\LibISDB\Windows\Filters\BonDriverSourceFilter.cpp)	LibISDBWindows	C:\Users\thund\Documents\TV\TVTest2\src\LibISDB\LibISDB\Base\ErrorHandler.hpp	148	
```
9d7432af365a255f2748a336a84c9d675c30c7e2 より前のバージョンでは正常にビルドできます。
## 環境
- OS: Windows 10 1909
- Compiler: Microsoft Visual Studio Community 2019 Version 16.5.2

VS2019を使っているのが原因かもしれませんが。

**Comment by masnagam** [comment]
最終的に大丈夫だと判断されたのですが， b9fb3c39883cfef612949e4db44361c0a8dea5d5 は必要な修正だったようですね．

Windows環境を構築して，ビルドエラーを解析してみます．

**Comment by masnagam** [comment]
以下の環境でビルドしてみたのですが，エラーは発生しませんでした．

* Windows 10 1909
* Microsoft Visual Studio Community 2019 Version 16.5.2
<details>
<summary>"Help | Copy Info"の内容</summary>
<pre>
Microsoft Visual Studio Community 2019
Version 16.5.2
VisualStudio.16.Release/16.5.2+29926.136
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA151
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
</pre>
</details>

ビルド手順は以下の通りです．

* Projects/LibISDB.slnを開く
* メニューから"Build | Build Solution"を実行

115件のワーニングが出ますが，エラーは出ませんでした．

念の為，以下も実施してみましたが，正常に機能しているように見えます．

* DebugおよびReleaseビルド
* libisdbtest.exeを実行
* tslogoextract.exeを引数無しで実行（起動できるかどうかだけを確認）

最近はVSを全く使わないので私の使い方がどこか間違っているのかもしれません．手順に誤りがある場合には指摘をお願いします．また，ビルド対象がLibISDBではなく，これを利用しているアプリケーション（例えばTVTest）である場合には，再現までのビルド手順を書いていただく必要があると思います．

個人的な意見ですが，`std::errc`に対する`std::make_error_code()`が適切に動作していないというのはSTLとしておかしな状態だと考えています．`std::is_error_code_enum<std::errc>`を定義するのではなく，何か別の箇所に異常を起こすような原因があるのではないかと考えています．

**Comment by estshorter** [comment]
再現実験ありがとうございます。

私のビルド手順は示して頂いたものと同じ(LibISDB.slnをビルド)ですので、私の環境の問題かもしれません。

**Comment by masnagam** [comment]
同じ手順なのに私のところで発生しないというのは，私が何か間違いを犯している可能性がありますので，もう一度確認してみます．

**Comment by masnagam** [comment]
どうやら間違って古いソースをビルドしていたようです．エラーの発生を確認できました．

**Comment by masnagam** [comment]
`<system_error>`に

```c++
// FUNCTION make_error_code
_NODISCARD inline error_code make_error_code(errc _Errno) noexcept {
    return error_code(static_cast<int>(_Errno), generic_category());
}
```

と定義されているので，とても不思議です．．

**Comment by masnagam** [comment]
あー，多分`std::errc`および`std:io_errc`以外，恐らく`int`が渡される可能性があるのだと推測されます．

```c++
// in system_error

    template <class _Enum, enable_if_t<is_error_code_enum_v<_Enum>, int> = 0>
    error_code(_Enum _Errcode) noexcept : _Myval(0), _Mycat(nullptr) {
        *this = make_error_code(_Errcode); // using ADL
    }
```

となっており，

```c++
// in system_error
template <>
struct is_error_code_enum<io_errc> : true_type {};
```

はあるのですが，`is_error_code_enum<errc>`がないので，`std::error_code`コンストラクターに置き換えるとエラーが出てしまい，`is_error_code_enum<errc>`を定義したものと推測されます．

ただ，恐らく何らかの理由により`is_error_code_enum<errc>`を定義していないのだと考えられるため，`is_error_code_enum<errc>`を定義するのではなく，別の方法で修正したほうが良さそうな気はします．

少し考えてみます．

**Comment by masnagam** [comment]
これですね．

```console
1>C:\Users\masnagam\source\repos\LibISDB\LibISDB\Base\ErrorHandler.hpp(148,1): message : while trying to match the argument list '(T)'
1>        with
1>        [
1>            T=LibISDB::EDCBPluginWriter::ErrorCode
1>        ] (compiling source file ..\LibISDB\Windows\Base\EDCBPluginWriter.cpp)
1>C:\Users\masnagam\source\repos\LibISDB\LibISDB\Windows\Base\EDCBPluginWriter.cpp(99): message : see reference to function template instantiation 'void LibISDB::ErrorHandler::SetError<LibISDB::EDCBPluginWriter::ErrorCode>(T,const LibISDB::CharType *,const LibISDB::CharType *,const LibISDB::CharType *) noexcept' being compiled
1>        with
1>        [
1>            T=LibISDB::EDCBPluginWriter::ErrorCode
1>        ]
```

`std::make_error_code`を定義しようとしていますが，
https://github.com/DBCTRADO/LibISDB/blob/master/LibISDB/Windows/Base/EDCBPluginWriter.cpp#L45

誤って`namespace LibISDB`に定義してしまっています．

あと，ここに定義してしまうと，ErrorHandler.hppからは`std::make_error_code`（インライン関数）は未定義だと処理されてしまうので，定義位置も変えないとビルドできないものと思われます．

ちゃんと修正する場合にはいろいろ書き換えないと無理っぽいですね．`#ifdef LIBISDB_WINDOWS`で前のコードを復活させてしまうのが一番手っ取り早いですが，とりあえず最初の実装意図に沿った修正を試みることにします．

**Comment by DBCTRADO** [comment]
すみません。LibISDB のビルドが通ったので問題ないかと思いましたが、LibIDSBWindows の方でエラーが出ましたね…。
一旦 Revert しました。
対処法はちょっと考えさせてください。

**Comment by masnagam** [comment]
@estshorter 6228db2ef7c74070456b4f376def8747ece8555b で修正されました．確認してみてください．

**Comment by estshorter** [comment]
ビルドできることを確認しました。ありがとうございました。
